[2025-03-29T05:15:58.989+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-29T05:15:59.007+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: forecast_sales_dag.forecast_aggregate_sales manual__2025-03-29T05:15:55.768943+00:00 [queued]>
[2025-03-29T05:15:59.018+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: forecast_sales_dag.forecast_aggregate_sales manual__2025-03-29T05:15:55.768943+00:00 [queued]>
[2025-03-29T05:15:59.021+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-03-29T05:15:59.059+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): forecast_aggregate_sales> on 2025-03-29 05:15:55.768943+00:00
[2025-03-29T05:15:59.067+0000] {standard_task_runner.py:72} INFO - Started process 1111 to run task
[2025-03-29T05:15:59.071+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'forecast_sales_dag', 'forecast_aggregate_sales', 'manual__2025-03-29T05:15:55.768943+00:00', '--job-id', '235', '--raw', '--subdir', 'DAGS_FOLDER/forecast_etl.py', '--cfg-path', '/tmp/tmpmluccfy8']
[2025-03-29T05:15:59.075+0000] {standard_task_runner.py:105} INFO - Job 235: Subtask forecast_aggregate_sales
[2025-03-29T05:15:59.150+0000] {task_command.py:467} INFO - Running <TaskInstance: forecast_sales_dag.forecast_aggregate_sales manual__2025-03-29T05:15:55.768943+00:00 [running]> on host 2eb76630dc09
[2025-03-29T05:15:59.270+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='forecast_sales_dag' AIRFLOW_CTX_TASK_ID='forecast_aggregate_sales' AIRFLOW_CTX_EXECUTION_DATE='2025-03-29T05:15:55.768943+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-29T05:15:55.768943+00:00'
[2025-03-29T05:15:59.273+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-29T05:15:59.276+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-29T05:15:59.278+0000] {logging_mixin.py:190} INFO - Current task name:forecast_aggregate_sales state:running start_date:2025-03-29 05:15:59.009325+00:00
[2025-03-29T05:15:59.281+0000] {logging_mixin.py:190} INFO - Dag name:forecast_sales_dag and current dag run status:running
[2025-03-29T05:15:59.284+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-29T05:15:59.358+0000] {forecaster.py:961} INFO - Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
[2025-03-29T05:15:59.400+0000] {filesystem.py:118} DEBUG - input tempfile: /tmp/tmp5s9rf_gp/aoew8skp.json
[2025-03-29T05:15:59.564+0000] {filesystem.py:118} DEBUG - input tempfile: /tmp/tmp5s9rf_gp/vunzi4nk.json
[2025-03-29T05:15:59.568+0000] {model.py:2042} DEBUG - idx 0
[2025-03-29T05:15:59.570+0000] {model.py:2043} DEBUG - running CmdStan, num_threads: None
[2025-03-29T05:15:59.572+0000] {model.py:2055} DEBUG - CmdStan args: ['/home/***/.local/lib/python3.9/site-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=27962', 'data', 'file=/tmp/tmp5s9rf_gp/aoew8skp.json', 'init=/tmp/tmp5s9rf_gp/vunzi4nk.json', 'output', 'file=/tmp/tmp5s9rf_gp/prophet_modelcvarkk3u/prophet_model-20250329051559.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
[2025-03-29T05:15:59.575+0000] {logging_mixin.py:190} WARNING - 05:15:59 - cmdstanpy - INFO - Chain [1] start processing
[2025-03-29T05:15:59.575+0000] {model.py:2058} INFO - Chain [1] start processing
[2025-03-29T05:15:59.664+0000] {logging_mixin.py:190} WARNING - 05:15:59 - cmdstanpy - INFO - Chain [1] done processing
[2025-03-29T05:15:59.664+0000] {model.py:2115} INFO - Chain [1] done processing
[2025-03-29T05:15:59.977+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/forecast_etl.py", line 39, in forecast_aggregate_sales
    future_df = forecast_df[forecast_df['Order Date'] > last_past_date].copy()
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/core/ops/common.py", line 76, in new_method
    return method(self, other)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/core/arraylike.py", line 56, in __gt__
    return self._cmp_method(other, operator.gt)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/core/series.py", line 5803, in _cmp_method
    res_values = ops.comparison_op(lvalues, rvalues, op)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/core/ops/array_ops.py", line 346, in comparison_op
    res_values = comp_method_OBJECT_ARRAY(op, lvalues, rvalues)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/core/ops/array_ops.py", line 131, in comp_method_OBJECT_ARRAY
    result = libops.scalar_compare(x.ravel(), y, op)
  File "ops.pyx", line 107, in pandas._libs.ops.scalar_compare
TypeError: '>' not supported between instances of 'datetime.date' and 'str'
[2025-03-29T05:16:00.001+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-29T05:16:00.003+0000] {logging_mixin.py:190} INFO - Task start:2025-03-29 05:15:59.009325+00:00 end:2025-03-29 05:16:00.000795+00:00 duration:0.99147
[2025-03-29T05:16:00.005+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): forecast_aggregate_sales> dag:<DAG: forecast_sales_dag> dagrun:<DagRun forecast_sales_dag @ 2025-03-29 05:15:55.768943+00:00: manual__2025-03-29T05:15:55.768943+00:00, state:running, queued_at: 2025-03-29 05:15:55.783907+00:00. externally triggered: True>
[2025-03-29T05:16:00.007+0000] {logging_mixin.py:190} INFO - Failure caused by '>' not supported between instances of 'datetime.date' and 'str'
[2025-03-29T05:16:00.009+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=forecast_sales_dag, task_id=forecast_aggregate_sales, run_id=manual__2025-03-29T05:15:55.768943+00:00, execution_date=20250329T051555, start_date=20250329T051559, end_date=20250329T051600
[2025-03-29T05:16:00.053+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-29T05:16:00.056+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 235 for task forecast_aggregate_sales ('>' not supported between instances of 'datetime.date' and 'str'; 1111)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/forecast_etl.py", line 39, in forecast_aggregate_sales
    future_df = forecast_df[forecast_df['Order Date'] > last_past_date].copy()
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/core/ops/common.py", line 76, in new_method
    return method(self, other)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/core/arraylike.py", line 56, in __gt__
    return self._cmp_method(other, operator.gt)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/core/series.py", line 5803, in _cmp_method
    res_values = ops.comparison_op(lvalues, rvalues, op)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/core/ops/array_ops.py", line 346, in comparison_op
    res_values = comp_method_OBJECT_ARRAY(op, lvalues, rvalues)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/core/ops/array_ops.py", line 131, in comp_method_OBJECT_ARRAY
    result = libops.scalar_compare(x.ravel(), y, op)
  File "ops.pyx", line 107, in pandas._libs.ops.scalar_compare
TypeError: '>' not supported between instances of 'datetime.date' and 'str'
[2025-03-29T05:16:00.092+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-29T05:16:00.118+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-29T05:16:00.142+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
