[2025-03-27T22:44:56.519+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-27T22:44:56.543+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: superstore_dag.extract_superstore_data manual__2025-03-27T22:44:53.508923+00:00 [queued]>
[2025-03-27T22:44:56.556+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: superstore_dag.extract_superstore_data manual__2025-03-27T22:44:53.508923+00:00 [queued]>
[2025-03-27T22:44:56.558+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-03-27T22:44:56.597+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): extract_superstore_data> on 2025-03-27 22:44:53.508923+00:00
[2025-03-27T22:44:56.605+0000] {standard_task_runner.py:72} INFO - Started process 384 to run task
[2025-03-27T22:44:56.609+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'superstore_dag', 'extract_superstore_data', 'manual__2025-03-27T22:44:53.508923+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/superstore_dag.py', '--cfg-path', '/tmp/tmp2io4ynke']
[2025-03-27T22:44:56.612+0000] {standard_task_runner.py:105} INFO - Job 10: Subtask extract_superstore_data
[2025-03-27T22:44:56.687+0000] {task_command.py:467} INFO - Running <TaskInstance: superstore_dag.extract_superstore_data manual__2025-03-27T22:44:53.508923+00:00 [running]> on host 4a86752196bf
[2025-03-27T22:44:56.804+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='superstore_dag' AIRFLOW_CTX_TASK_ID='extract_superstore_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-27T22:44:53.508923+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-27T22:44:53.508923+00:00'
[2025-03-27T22:44:56.807+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-27T22:44:56.809+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-27T22:44:56.811+0000] {logging_mixin.py:190} INFO - Current task name:extract_superstore_data state:running start_date:2025-03-27 22:44:56.545837+00:00
[2025-03-27T22:44:56.814+0000] {logging_mixin.py:190} INFO - Dag name:superstore_dag and current dag run status:running
[2025-03-27T22:44:56.816+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-27T22:44:56.826+0000] {base.py:84} INFO - Retrieving connection '***_maj_db'
[2025-03-27T22:44:56.836+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "src/pymssql/_pymssql.pyx", line 650, in pymssql._pymssql.connect
  File "src/pymssql/_mssql.pyx", line 2158, in pymssql._mssql.connect
  File "src/pymssql/_mssql.pyx", line 712, in pymssql._mssql.MSSQLConnection.__init__
  File "src/pymssql/_mssql.pyx", line 1884, in pymssql._mssql.maybe_raise_MSSQLDatabaseException
  File "src/pymssql/_mssql.pyx", line 1901, in pymssql._mssql.raise_MSSQLDatabaseException
pymssql._mssql.MSSQLDatabaseException: (20009, b'DB-Lib error message 20009, severity 9:\nUnable to connect: Adaptive Server is unavailable or does not exist (DESKTOP-P0UUQSR)\n')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/superstore_dag.py", line 18, in extract_superstore_data
    df = hook.get_pandas_df(sql=query)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/common/sql/hooks/sql.py", line 399, in get_pandas_df
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/microsoft/mssql/hooks/mssql.py", line 103, in get_conn
    return pymssql.connect(
  File "src/pymssql/_pymssql.pyx", line 659, in pymssql._pymssql.connect
pymssql.exceptions.OperationalError: (20009, b'DB-Lib error message 20009, severity 9:\nUnable to connect: Adaptive Server is unavailable or does not exist (DESKTOP-P0UUQSR)\n')
[2025-03-27T22:44:56.857+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-27T22:44:56.858+0000] {logging_mixin.py:190} INFO - Task start:2025-03-27 22:44:56.545837+00:00 end:2025-03-27 22:44:56.856515+00:00 duration:0.310678
[2025-03-27T22:44:56.860+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): extract_superstore_data> dag:<DAG: superstore_dag> dagrun:<DagRun superstore_dag @ 2025-03-27 22:44:53.508923+00:00: manual__2025-03-27T22:44:53.508923+00:00, state:running, queued_at: 2025-03-27 22:44:53.528742+00:00. externally triggered: True>
[2025-03-27T22:44:56.862+0000] {logging_mixin.py:190} INFO - Failure caused by (20009, b'DB-Lib error message 20009, severity 9:\nUnable to connect: Adaptive Server is unavailable or does not exist (DESKTOP-P0UUQSR)\n')
[2025-03-27T22:44:56.864+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=superstore_dag, task_id=extract_superstore_data, run_id=manual__2025-03-27T22:44:53.508923+00:00, execution_date=20250327T224453, start_date=20250327T224456, end_date=20250327T224456
[2025-03-27T22:44:56.968+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-27T22:44:56.973+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 10 for task extract_superstore_data ((20009, b'DB-Lib error message 20009, severity 9:\nUnable to connect: Adaptive Server is unavailable or does not exist (DESKTOP-P0UUQSR)\n'); 384)
Traceback (most recent call last):
  File "src/pymssql/_pymssql.pyx", line 650, in pymssql._pymssql.connect
  File "src/pymssql/_mssql.pyx", line 2158, in pymssql._mssql.connect
  File "src/pymssql/_mssql.pyx", line 712, in pymssql._mssql.MSSQLConnection.__init__
  File "src/pymssql/_mssql.pyx", line 1884, in pymssql._mssql.maybe_raise_MSSQLDatabaseException
  File "src/pymssql/_mssql.pyx", line 1901, in pymssql._mssql.raise_MSSQLDatabaseException
pymssql._mssql.MSSQLDatabaseException: (20009, b'DB-Lib error message 20009, severity 9:\nUnable to connect: Adaptive Server is unavailable or does not exist (DESKTOP-P0UUQSR)\n')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/superstore_dag.py", line 18, in extract_superstore_data
    df = hook.get_pandas_df(sql=query)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/common/sql/hooks/sql.py", line 399, in get_pandas_df
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/microsoft/mssql/hooks/mssql.py", line 103, in get_conn
    return pymssql.connect(
  File "src/pymssql/_pymssql.pyx", line 659, in pymssql._pymssql.connect
pymssql.exceptions.OperationalError: (20009, b'DB-Lib error message 20009, severity 9:\nUnable to connect: Adaptive Server is unavailable or does not exist (DESKTOP-P0UUQSR)\n')
[2025-03-27T22:44:57.025+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-27T22:44:57.052+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-27T22:44:57.076+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
