[2025-03-29T05:32:51.657+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-29T05:32:51.681+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: forecast_sales_dag.load_data_to_prod_db manual__2025-03-29T05:27:38.340011+00:00 [queued]>
[2025-03-29T05:32:51.694+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: forecast_sales_dag.load_data_to_prod_db manual__2025-03-29T05:27:38.340011+00:00 [queued]>
[2025-03-29T05:32:51.696+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2025-03-29T05:32:51.739+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): load_data_to_prod_db> on 2025-03-29 05:27:38.340011+00:00
[2025-03-29T05:32:51.750+0000] {standard_task_runner.py:72} INFO - Started process 1556 to run task
[2025-03-29T05:32:51.755+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'forecast_sales_dag', 'load_data_to_prod_db', 'manual__2025-03-29T05:27:38.340011+00:00', '--job-id', '251', '--raw', '--subdir', 'DAGS_FOLDER/forecast_etl.py', '--cfg-path', '/tmp/tmpigsk8khr']
[2025-03-29T05:32:51.758+0000] {standard_task_runner.py:105} INFO - Job 251: Subtask load_data_to_prod_db
[2025-03-29T05:32:51.838+0000] {task_command.py:467} INFO - Running <TaskInstance: forecast_sales_dag.load_data_to_prod_db manual__2025-03-29T05:27:38.340011+00:00 [running]> on host 2eb76630dc09
[2025-03-29T05:32:51.959+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='forecast_sales_dag' AIRFLOW_CTX_TASK_ID='load_data_to_prod_db' AIRFLOW_CTX_EXECUTION_DATE='2025-03-29T05:27:38.340011+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-29T05:27:38.340011+00:00'
[2025-03-29T05:32:51.963+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-29T05:32:51.965+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-29T05:32:51.967+0000] {logging_mixin.py:190} INFO - Current task name:load_data_to_prod_db state:running start_date:2025-03-29 05:32:51.684036+00:00
[2025-03-29T05:32:51.969+0000] {logging_mixin.py:190} INFO - Dag name:forecast_sales_dag and current dag run status:running
[2025-03-29T05:32:51.971+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-29T05:32:52.003+0000] {warnings.py:109} WARNING - /opt/***/dags/forecast_etl.py:69: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  forecast_metrics_df = pd.read_json(forecast_metrics_json, orient='records')

[2025-03-29T05:32:52.020+0000] {logging_mixin.py:190} INFO - Checking and potentially creating table: forecast_past_future_sales
[2025-03-29T05:32:52.032+0000] {base.py:84} INFO - Retrieving connection '***_default'
[2025-03-29T05:32:52.072+0000] {sql.py:624} INFO - Running statement: 
                IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'forecast_past_future_sales')
                BEGIN
                    CREATE TABLE forecast_past_future_sales ([Order Date] DATETIME, [Aggregate Sales] FLOAT, [label] VARCHAR(MAX));
                    PRINT 'Table forecast_past_future_sales created successfully.';
                END
            , parameters: None
[2025-03-29T05:32:52.136+0000] {logging_mixin.py:190} INFO - Table forecast_past_future_sales exists or was just created.
[2025-03-29T05:32:52.139+0000] {logging_mixin.py:190} INFO - Checking and potentially creating table: forecast_metrics
[2025-03-29T05:32:52.170+0000] {sql.py:624} INFO - Running statement: 
                IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'forecast_metrics')
                BEGIN
                    CREATE TABLE forecast_metrics ([Metric] VARCHAR(MAX), [Value] FLOAT);
                    PRINT 'Table forecast_metrics created successfully.';
                END
            , parameters: None
[2025-03-29T05:32:52.187+0000] {logging_mixin.py:190} INFO - Table forecast_metrics exists or was just created.
[2025-03-29T05:32:52.189+0000] {logging_mixin.py:190} INFO - Truncating table: forecast_past_future_sales
[2025-03-29T05:32:52.222+0000] {sql.py:624} INFO - Running statement: TRUNCATE TABLE forecast_past_future_sales, parameters: None
[2025-03-29T05:32:52.231+0000] {logging_mixin.py:190} INFO - Loading 1602 rows into forecast_past_future_sales
[2025-03-29T05:32:52.269+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "src/pymssql/_pymssql.pyx", line 447, in pymssql._pymssql.Cursor.execute
  File "src/pymssql/_mssql.pyx", line 1125, in pymssql._mssql.MSSQLConnection.execute_query
  File "src/pymssql/_mssql.pyx", line 1156, in pymssql._mssql.MSSQLConnection.execute_query
  File "src/pymssql/_mssql.pyx", line 1289, in pymssql._mssql.MSSQLConnection.format_and_run_query
  File "src/pymssql/_mssql.pyx", line 1855, in pymssql._mssql.check_cancel_and_raise
  File "src/pymssql/_mssql.pyx", line 1901, in pymssql._mssql.raise_MSSQLDatabaseException
pymssql._mssql.MSSQLDatabaseException: (8114, b'Error converting data type nvarchar to float.DB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\n')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/forecast_etl.py", line 112, in load_data_to_prod_db
    load_df_to_mssql('forecast_past_future_sales', past_future_sales_df, hook)
  File "/opt/airflow/dags/forecast_etl.py", line 106, in load_df_to_mssql
    hook.insert_rows(table=table_name, rows=df.to_records(index=False), target_fields=df.columns.tolist(),
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/common/sql/hooks/sql.py", line 754, in insert_rows
    cur.execute(sql, values)
  File "src/pymssql/_pymssql.pyx", line 465, in pymssql._pymssql.Cursor.execute
pymssql.exceptions.OperationalError: (8114, b'Error converting data type nvarchar to float.DB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\n')
[2025-03-29T05:32:52.282+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-29T05:32:52.284+0000] {logging_mixin.py:190} INFO - Task start:2025-03-29 05:32:51.684036+00:00 end:2025-03-29 05:32:52.282025+00:00 duration:0.597989
[2025-03-29T05:32:52.286+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): load_data_to_prod_db> dag:<DAG: forecast_sales_dag> dagrun:<DagRun forecast_sales_dag @ 2025-03-29 05:27:38.340011+00:00: manual__2025-03-29T05:27:38.340011+00:00, state:running, queued_at: 2025-03-29 05:27:38.360148+00:00. externally triggered: True>
[2025-03-29T05:32:52.287+0000] {logging_mixin.py:190} INFO - Failure caused by (8114, b'Error converting data type nvarchar to float.DB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\n')
[2025-03-29T05:32:52.289+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=forecast_sales_dag, task_id=load_data_to_prod_db, run_id=manual__2025-03-29T05:27:38.340011+00:00, execution_date=20250329T052738, start_date=20250329T053251, end_date=20250329T053252
[2025-03-29T05:32:52.321+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-29T05:32:52.323+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 251 for task load_data_to_prod_db ((8114, b'Error converting data type nvarchar to float.DB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\n'); 1556)
Traceback (most recent call last):
  File "src/pymssql/_pymssql.pyx", line 447, in pymssql._pymssql.Cursor.execute
  File "src/pymssql/_mssql.pyx", line 1125, in pymssql._mssql.MSSQLConnection.execute_query
  File "src/pymssql/_mssql.pyx", line 1156, in pymssql._mssql.MSSQLConnection.execute_query
  File "src/pymssql/_mssql.pyx", line 1289, in pymssql._mssql.MSSQLConnection.format_and_run_query
  File "src/pymssql/_mssql.pyx", line 1855, in pymssql._mssql.check_cancel_and_raise
  File "src/pymssql/_mssql.pyx", line 1901, in pymssql._mssql.raise_MSSQLDatabaseException
pymssql._mssql.MSSQLDatabaseException: (8114, b'Error converting data type nvarchar to float.DB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\n')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/forecast_etl.py", line 112, in load_data_to_prod_db
    load_df_to_mssql('forecast_past_future_sales', past_future_sales_df, hook)
  File "/opt/airflow/dags/forecast_etl.py", line 106, in load_df_to_mssql
    hook.insert_rows(table=table_name, rows=df.to_records(index=False), target_fields=df.columns.tolist(),
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/common/sql/hooks/sql.py", line 754, in insert_rows
    cur.execute(sql, values)
  File "src/pymssql/_pymssql.pyx", line 465, in pymssql._pymssql.Cursor.execute
pymssql.exceptions.OperationalError: (8114, b'Error converting data type nvarchar to float.DB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\n')
[2025-03-29T05:32:52.372+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-29T05:32:52.420+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-29T05:32:52.447+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
