[2025-03-27T22:58:48.990+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-27T22:58:49.018+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: superstore_dag.compare_and_save_records manual__2025-03-27T22:58:42.855849+00:00 [queued]>
[2025-03-27T22:58:49.035+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: superstore_dag.compare_and_save_records manual__2025-03-27T22:58:42.855849+00:00 [queued]>
[2025-03-27T22:58:49.038+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-03-27T22:58:49.082+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): compare_and_save_records> on 2025-03-27 22:58:42.855849+00:00
[2025-03-27T22:58:49.089+0000] {standard_task_runner.py:72} INFO - Started process 586 to run task
[2025-03-27T22:58:49.093+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'superstore_dag', 'compare_and_save_records', 'manual__2025-03-27T22:58:42.855849+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/superstore_dag.py', '--cfg-path', '/tmp/tmprvsgg5i5']
[2025-03-27T22:58:49.096+0000] {standard_task_runner.py:105} INFO - Job 15: Subtask compare_and_save_records
[2025-03-27T22:58:49.176+0000] {task_command.py:467} INFO - Running <TaskInstance: superstore_dag.compare_and_save_records manual__2025-03-27T22:58:42.855849+00:00 [running]> on host 4a86752196bf
[2025-03-27T22:58:49.297+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='superstore_dag' AIRFLOW_CTX_TASK_ID='compare_and_save_records' AIRFLOW_CTX_EXECUTION_DATE='2025-03-27T22:58:42.855849+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-27T22:58:42.855849+00:00'
[2025-03-27T22:58:49.301+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-27T22:58:49.303+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-27T22:58:49.305+0000] {logging_mixin.py:190} INFO - Current task name:compare_and_save_records state:running start_date:2025-03-27 22:58:49.021413+00:00
[2025-03-27T22:58:49.308+0000] {logging_mixin.py:190} INFO - Dag name:superstore_dag and current dag run status:running
[2025-03-27T22:58:49.310+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-27T22:58:49.457+0000] {logging_mixin.py:190} INFO - Number of new records/rows added: 9994
[2025-03-27T22:58:49.460+0000] {logging_mixin.py:190} INFO - Number of old records modified: 0
[2025-03-27T22:58:49.478+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/superstore_dag.py", line 59, in compare_and_save_records
    new_records.to_csv(NEW_RECORDS_FILE, index=False)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/core/generic.py", line 3902, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/formats/format.py", line 1152, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/formats/csvs.py", line 247, in save
    with get_handle(
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/common.py", line 739, in get_handle
    check_parent_directory(str(handle))
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/common.py", line 604, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: '/data/extract'
[2025-03-27T22:58:49.527+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-27T22:58:49.529+0000] {logging_mixin.py:190} INFO - Task start:2025-03-27 22:58:49.021413+00:00 end:2025-03-27 22:58:49.526233+00:00 duration:0.50482
[2025-03-27T22:58:49.532+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): compare_and_save_records> dag:<DAG: superstore_dag> dagrun:<DagRun superstore_dag @ 2025-03-27 22:58:42.855849+00:00: manual__2025-03-27T22:58:42.855849+00:00, state:running, queued_at: 2025-03-27 22:58:42.884994+00:00. externally triggered: True>
[2025-03-27T22:58:49.534+0000] {logging_mixin.py:190} INFO - Failure caused by Cannot save file into a non-existent directory: '/data/extract'
[2025-03-27T22:58:49.535+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=superstore_dag, task_id=compare_and_save_records, run_id=manual__2025-03-27T22:58:42.855849+00:00, execution_date=20250327T225842, start_date=20250327T225849, end_date=20250327T225849
[2025-03-27T22:58:49.586+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-27T22:58:49.588+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 15 for task compare_and_save_records (Cannot save file into a non-existent directory: '/data/extract'; 586)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/superstore_dag.py", line 59, in compare_and_save_records
    new_records.to_csv(NEW_RECORDS_FILE, index=False)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/core/generic.py", line 3902, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/formats/format.py", line 1152, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/formats/csvs.py", line 247, in save
    with get_handle(
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/common.py", line 739, in get_handle
    check_parent_directory(str(handle))
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/common.py", line 604, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: '/data/extract'
[2025-03-27T22:58:49.629+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-27T22:58:49.660+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-27T22:58:49.685+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
