[2025-03-28T14:59:09.948+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-28T14:59:09.987+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: superstore_dag.extract_superstore_data manual__2025-03-28T14:54:02.942832+00:00 [queued]>
[2025-03-28T14:59:10.001+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: superstore_dag.extract_superstore_data manual__2025-03-28T14:54:02.942832+00:00 [queued]>
[2025-03-28T14:59:10.017+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2025-03-28T14:59:10.057+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): extract_superstore_data> on 2025-03-28 14:54:02.942832+00:00
[2025-03-28T14:59:10.069+0000] {standard_task_runner.py:72} INFO - Started process 1971 to run task
[2025-03-28T14:59:10.078+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'superstore_dag', 'extract_superstore_data', 'manual__2025-03-28T14:54:02.942832+00:00', '--job-id', '100', '--raw', '--subdir', 'DAGS_FOLDER/superstore_dag.py', '--cfg-path', '/tmp/tmp_kv0q6_h']
[2025-03-28T14:59:10.081+0000] {standard_task_runner.py:105} INFO - Job 100: Subtask extract_superstore_data
[2025-03-28T14:59:10.159+0000] {task_command.py:467} INFO - Running <TaskInstance: superstore_dag.extract_superstore_data manual__2025-03-28T14:54:02.942832+00:00 [running]> on host b7fc87b83960
[2025-03-28T14:59:10.335+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='superstore_dag' AIRFLOW_CTX_TASK_ID='extract_superstore_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-28T14:54:02.942832+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-28T14:54:02.942832+00:00'
[2025-03-28T14:59:10.338+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-28T14:59:10.340+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-28T14:59:10.342+0000] {logging_mixin.py:190} INFO - Current task name:extract_superstore_data state:running start_date:2025-03-28 14:59:09.990069+00:00
[2025-03-28T14:59:10.345+0000] {logging_mixin.py:190} INFO - Dag name:superstore_dag and current dag run status:running
[2025-03-28T14:59:10.347+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-28T14:59:10.360+0000] {base.py:84} INFO - Retrieving connection '***_maj_db'
[2025-03-28T14:59:10.399+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.9/site-packages/***/providers/common/sql/hooks/sql.py:400: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return psql.read_sql(sql, con=conn, params=parameters, **kwargs)

[2025-03-28T14:59:10.409+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "src/pymssql/_pymssql.pyx", line 447, in pymssql._pymssql.Cursor.execute
  File "src/pymssql/_mssql.pyx", line 1125, in pymssql._mssql.MSSQLConnection.execute_query
  File "src/pymssql/_mssql.pyx", line 1156, in pymssql._mssql.MSSQLConnection.execute_query
  File "src/pymssql/_mssql.pyx", line 1289, in pymssql._mssql.MSSQLConnection.format_and_run_query
  File "src/pymssql/_mssql.pyx", line 1855, in pymssql._mssql.check_cancel_and_raise
  File "src/pymssql/_mssql.pyx", line 1901, in pymssql._mssql.raise_MSSQLDatabaseException
pymssql._mssql.MSSQLDatabaseException: (102, b"Incorrect syntax near '*'.DB-Lib error message 20018, severity 15:\nGeneral SQL Server error: Check messages from the SQL Server\n")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/sql.py", line 2262, in execute
    cur.execute(sql, *args)
  File "src/pymssql/_pymssql.pyx", line 462, in pymssql._pymssql.Cursor.execute
pymssql.exceptions.ProgrammingError: (102, b"Incorrect syntax near '*'.DB-Lib error message 20018, severity 15:\nGeneral SQL Server error: Check messages from the SQL Server\n")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/superstore_dag.py", line 32, in extract_superstore_data
    df = hook.get_pandas_df(sql=query)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/common/sql/hooks/sql.py", line 400, in get_pandas_df
    return psql.read_sql(sql, con=conn, params=parameters, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/sql.py", line 654, in read_sql
    return pandas_sql.read_query(
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/sql.py", line 2326, in read_query
    cursor = self.execute(sql, params)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/sql.py", line 2274, in execute
    raise ex from exc
pandas.errors.DatabaseError: Execution failed on sql 'SELECT TOP  * FROM superstore': (102, b"Incorrect syntax near '*'.DB-Lib error message 20018, severity 15:\nGeneral SQL Server error: Check messages from the SQL Server\n")
[2025-03-28T14:59:10.430+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-28T14:59:10.433+0000] {logging_mixin.py:190} INFO - Task start:2025-03-28 14:59:09.990069+00:00 end:2025-03-28 14:59:10.430416+00:00 duration:0.440347
[2025-03-28T14:59:10.435+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): extract_superstore_data> dag:<DAG: superstore_dag> dagrun:<DagRun superstore_dag @ 2025-03-28 14:54:02.942832+00:00: manual__2025-03-28T14:54:02.942832+00:00, state:running, queued_at: 2025-03-28 14:54:02.955363+00:00. externally triggered: True>
[2025-03-28T14:59:10.438+0000] {logging_mixin.py:190} INFO - Failure caused by Execution failed on sql 'SELECT TOP  * FROM superstore': (102, b"Incorrect syntax near '*'.DB-Lib error message 20018, severity 15:\nGeneral SQL Server error: Check messages from the SQL Server\n")
[2025-03-28T14:59:10.440+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=superstore_dag, task_id=extract_superstore_data, run_id=manual__2025-03-28T14:54:02.942832+00:00, execution_date=20250328T145402, start_date=20250328T145909, end_date=20250328T145910
[2025-03-28T14:59:10.520+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-28T14:59:10.523+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 100 for task extract_superstore_data (Execution failed on sql 'SELECT TOP  * FROM superstore': (102, b"Incorrect syntax near '*'.DB-Lib error message 20018, severity 15:\nGeneral SQL Server error: Check messages from the SQL Server\n"); 1971)
Traceback (most recent call last):
  File "src/pymssql/_pymssql.pyx", line 447, in pymssql._pymssql.Cursor.execute
  File "src/pymssql/_mssql.pyx", line 1125, in pymssql._mssql.MSSQLConnection.execute_query
  File "src/pymssql/_mssql.pyx", line 1156, in pymssql._mssql.MSSQLConnection.execute_query
  File "src/pymssql/_mssql.pyx", line 1289, in pymssql._mssql.MSSQLConnection.format_and_run_query
  File "src/pymssql/_mssql.pyx", line 1855, in pymssql._mssql.check_cancel_and_raise
  File "src/pymssql/_mssql.pyx", line 1901, in pymssql._mssql.raise_MSSQLDatabaseException
pymssql._mssql.MSSQLDatabaseException: (102, b"Incorrect syntax near '*'.DB-Lib error message 20018, severity 15:\nGeneral SQL Server error: Check messages from the SQL Server\n")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/sql.py", line 2262, in execute
    cur.execute(sql, *args)
  File "src/pymssql/_pymssql.pyx", line 462, in pymssql._pymssql.Cursor.execute
pymssql.exceptions.ProgrammingError: (102, b"Incorrect syntax near '*'.DB-Lib error message 20018, severity 15:\nGeneral SQL Server error: Check messages from the SQL Server\n")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/superstore_dag.py", line 32, in extract_superstore_data
    df = hook.get_pandas_df(sql=query)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/common/sql/hooks/sql.py", line 400, in get_pandas_df
    return psql.read_sql(sql, con=conn, params=parameters, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/sql.py", line 654, in read_sql
    return pandas_sql.read_query(
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/sql.py", line 2326, in read_query
    cursor = self.execute(sql, params)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/sql.py", line 2274, in execute
    raise ex from exc
pandas.errors.DatabaseError: Execution failed on sql 'SELECT TOP  * FROM superstore': (102, b"Incorrect syntax near '*'.DB-Lib error message 20018, severity 15:\nGeneral SQL Server error: Check messages from the SQL Server\n")
[2025-03-28T14:59:10.574+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-28T14:59:10.603+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-28T14:59:10.629+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
