[2025-03-28T17:31:50.931+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-28T17:31:50.956+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: superstore_dag.forecast_aggregate_sales manual__2025-03-28T17:31:29.322473+00:00 [queued]>
[2025-03-28T17:31:50.974+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: superstore_dag.forecast_aggregate_sales manual__2025-03-28T17:31:29.322473+00:00 [queued]>
[2025-03-28T17:31:50.993+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-03-28T17:31:51.032+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): forecast_aggregate_sales> on 2025-03-28 17:31:29.322473+00:00
[2025-03-28T17:31:51.044+0000] {standard_task_runner.py:72} INFO - Started process 4639 to run task
[2025-03-28T17:31:51.049+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'superstore_dag', 'forecast_aggregate_sales', 'manual__2025-03-28T17:31:29.322473+00:00', '--job-id', '172', '--raw', '--subdir', 'DAGS_FOLDER/superstore_dag.py', '--cfg-path', '/tmp/tmpxifoejh8']
[2025-03-28T17:31:51.051+0000] {standard_task_runner.py:105} INFO - Job 172: Subtask forecast_aggregate_sales
[2025-03-28T17:31:51.145+0000] {task_command.py:467} INFO - Running <TaskInstance: superstore_dag.forecast_aggregate_sales manual__2025-03-28T17:31:29.322473+00:00 [running]> on host b7fc87b83960
[2025-03-28T17:31:51.283+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='superstore_dag' AIRFLOW_CTX_TASK_ID='forecast_aggregate_sales' AIRFLOW_CTX_EXECUTION_DATE='2025-03-28T17:31:29.322473+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-28T17:31:29.322473+00:00'
[2025-03-28T17:31:51.286+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-28T17:31:51.288+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-28T17:31:51.290+0000] {logging_mixin.py:190} INFO - Current task name:forecast_aggregate_sales state:running start_date:2025-03-28 17:31:50.959007+00:00
[2025-03-28T17:31:51.291+0000] {logging_mixin.py:190} INFO - Dag name:superstore_dag and current dag run status:running
[2025-03-28T17:31:51.292+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-28T17:31:51.341+0000] {forecaster.py:961} INFO - Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
[2025-03-28T17:31:51.363+0000] {filesystem.py:118} DEBUG - input tempfile: /tmp/tmpyi5u062i/h88pl8n8.json
[2025-03-28T17:31:51.447+0000] {filesystem.py:118} DEBUG - input tempfile: /tmp/tmpyi5u062i/rfscsnfo.json
[2025-03-28T17:31:51.449+0000] {model.py:2042} DEBUG - idx 0
[2025-03-28T17:31:51.451+0000] {model.py:2043} DEBUG - running CmdStan, num_threads: None
[2025-03-28T17:31:51.452+0000] {model.py:2055} DEBUG - CmdStan args: ['/home/***/.local/lib/python3.9/site-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=38608', 'data', 'file=/tmp/tmpyi5u062i/h88pl8n8.json', 'init=/tmp/tmpyi5u062i/rfscsnfo.json', 'output', 'file=/tmp/tmpyi5u062i/prophet_model_wyhzww1/prophet_model-20250328173151.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
[2025-03-28T17:31:51.454+0000] {logging_mixin.py:190} WARNING - 17:31:51 - cmdstanpy - INFO - Chain [1] start processing
[2025-03-28T17:31:51.454+0000] {model.py:2058} INFO - Chain [1] start processing
[2025-03-28T17:31:51.533+0000] {logging_mixin.py:190} WARNING - 17:31:51 - cmdstanpy - INFO - Chain [1] done processing
[2025-03-28T17:31:51.533+0000] {model.py:2115} INFO - Chain [1] done processing
[2025-03-28T17:31:51.865+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/superstore_dag.py", line 214, in forecast_aggregate_sales
    past_future_sales.to_csv(os.path.join(OUTPUT_DIR, 'past_future_sales.csv'), index=False)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/core/generic.py", line 3902, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/formats/format.py", line 1152, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/formats/csvs.py", line 247, in save
    with get_handle(
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
PermissionError: [Errno 13] Permission denied: '/opt/airflow/logs/extracted_data/past_future_sales.csv'
[2025-03-28T17:31:51.902+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-28T17:31:51.905+0000] {logging_mixin.py:190} INFO - Task start:2025-03-28 17:31:50.959007+00:00 end:2025-03-28 17:31:51.901733+00:00 duration:0.942726
[2025-03-28T17:31:51.907+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): forecast_aggregate_sales> dag:<DAG: superstore_dag> dagrun:<DagRun superstore_dag @ 2025-03-28 17:31:29.322473+00:00: manual__2025-03-28T17:31:29.322473+00:00, state:running, queued_at: 2025-03-28 17:31:29.340500+00:00. externally triggered: True>
[2025-03-28T17:31:51.909+0000] {logging_mixin.py:190} INFO - Failure caused by [Errno 13] Permission denied: '/opt/***/logs/extracted_data/past_future_sales.csv'
[2025-03-28T17:31:51.913+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=superstore_dag, task_id=forecast_aggregate_sales, run_id=manual__2025-03-28T17:31:29.322473+00:00, execution_date=20250328T173129, start_date=20250328T173150, end_date=20250328T173151
[2025-03-28T17:31:51.967+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-28T17:31:51.971+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 172 for task forecast_aggregate_sales ([Errno 13] Permission denied: '/opt/airflow/logs/extracted_data/past_future_sales.csv'; 4639)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/superstore_dag.py", line 214, in forecast_aggregate_sales
    past_future_sales.to_csv(os.path.join(OUTPUT_DIR, 'past_future_sales.csv'), index=False)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/core/generic.py", line 3902, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/formats/format.py", line 1152, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/formats/csvs.py", line 247, in save
    with get_handle(
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
PermissionError: [Errno 13] Permission denied: '/opt/airflow/logs/extracted_data/past_future_sales.csv'
[2025-03-28T17:31:52.027+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-28T17:31:52.064+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-28T17:31:52.086+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
