[2025-03-28T14:36:53.710+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-28T14:36:53.728+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: superstore_dag.forecast_aggregate_sales manual__2025-03-28T14:31:30.119149+00:00 [queued]>
[2025-03-28T14:36:53.738+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: superstore_dag.forecast_aggregate_sales manual__2025-03-28T14:31:30.119149+00:00 [queued]>
[2025-03-28T14:36:53.742+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2025-03-28T14:36:53.782+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): forecast_aggregate_sales> on 2025-03-28 14:31:30.119149+00:00
[2025-03-28T14:36:53.791+0000] {standard_task_runner.py:72} INFO - Started process 1389 to run task
[2025-03-28T14:36:53.796+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'superstore_dag', 'forecast_aggregate_sales', 'manual__2025-03-28T14:31:30.119149+00:00', '--job-id', '86', '--raw', '--subdir', 'DAGS_FOLDER/superstore_dag.py', '--cfg-path', '/tmp/tmp9tajaiy8']
[2025-03-28T14:36:53.798+0000] {standard_task_runner.py:105} INFO - Job 86: Subtask forecast_aggregate_sales
[2025-03-28T14:36:53.872+0000] {task_command.py:467} INFO - Running <TaskInstance: superstore_dag.forecast_aggregate_sales manual__2025-03-28T14:31:30.119149+00:00 [running]> on host b7fc87b83960
[2025-03-28T14:36:53.998+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='superstore_dag' AIRFLOW_CTX_TASK_ID='forecast_aggregate_sales' AIRFLOW_CTX_EXECUTION_DATE='2025-03-28T14:31:30.119149+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-28T14:31:30.119149+00:00'
[2025-03-28T14:36:54.001+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-28T14:36:54.003+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-28T14:36:54.005+0000] {logging_mixin.py:190} INFO - Current task name:forecast_aggregate_sales state:running start_date:2025-03-28 14:36:53.730250+00:00
[2025-03-28T14:36:54.008+0000] {logging_mixin.py:190} INFO - Dag name:superstore_dag and current dag run status:running
[2025-03-28T14:36:54.010+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-28T14:36:54.072+0000] {forecaster.py:961} INFO - Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
[2025-03-28T14:36:54.096+0000] {filesystem.py:118} DEBUG - input tempfile: /tmp/tmp33z1dc80/y535sxfj.json
[2025-03-28T14:36:54.188+0000] {filesystem.py:118} DEBUG - input tempfile: /tmp/tmp33z1dc80/yqej5hu5.json
[2025-03-28T14:36:54.191+0000] {model.py:2042} DEBUG - idx 0
[2025-03-28T14:36:54.194+0000] {model.py:2043} DEBUG - running CmdStan, num_threads: None
[2025-03-28T14:36:54.196+0000] {model.py:2055} DEBUG - CmdStan args: ['/home/***/.local/lib/python3.9/site-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=82817', 'data', 'file=/tmp/tmp33z1dc80/y535sxfj.json', 'init=/tmp/tmp33z1dc80/yqej5hu5.json', 'output', 'file=/tmp/tmp33z1dc80/prophet_model2nsgal1y/prophet_model-20250328143654.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
[2025-03-28T14:36:54.198+0000] {logging_mixin.py:190} WARNING - 14:36:54 - cmdstanpy - INFO - Chain [1] start processing
[2025-03-28T14:36:54.198+0000] {model.py:2058} INFO - Chain [1] start processing
[2025-03-28T14:36:54.264+0000] {logging_mixin.py:190} WARNING - 14:36:54 - cmdstanpy - INFO - Chain [1] done processing
[2025-03-28T14:36:54.264+0000] {model.py:2115} INFO - Chain [1] done processing
[2025-03-28T14:36:54.272+0000] {logging_mixin.py:190} INFO - Last date in aggregate sales: 2017-12-30
[2025-03-28T14:36:54.425+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/superstore_dag.py", line 218, in forecast_aggregate_sales
    rmse = np.sqrt(mean_squared_error(actual_sales, past_predictions[:len(aggregate_sales_df)]))
  File "/home/airflow/.local/lib/python3.9/site-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/sklearn/metrics/_regression.py", line 565, in mean_squared_error
    _check_reg_targets_with_floating_dtype(
  File "/home/airflow/.local/lib/python3.9/site-packages/sklearn/metrics/_regression.py", line 198, in _check_reg_targets_with_floating_dtype
    y_type, y_true, y_pred, multioutput = _check_reg_targets(
  File "/home/airflow/.local/lib/python3.9/site-packages/sklearn/metrics/_regression.py", line 104, in _check_reg_targets
    check_consistent_length(y_true, y_pred)
  File "/home/airflow/.local/lib/python3.9/site-packages/sklearn/utils/validation.py", line 475, in check_consistent_length
    raise ValueError(
ValueError: Found input variables with inconsistent numbers of samples: [1012, 365]
[2025-03-28T14:36:54.451+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-28T14:36:54.453+0000] {logging_mixin.py:190} INFO - Task start:2025-03-28 14:36:53.730250+00:00 end:2025-03-28 14:36:54.450840+00:00 duration:0.72059
[2025-03-28T14:36:54.454+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): forecast_aggregate_sales> dag:<DAG: superstore_dag> dagrun:<DagRun superstore_dag @ 2025-03-28 14:31:30.119149+00:00: manual__2025-03-28T14:31:30.119149+00:00, state:running, queued_at: 2025-03-28 14:31:30.128800+00:00. externally triggered: True>
[2025-03-28T14:36:54.455+0000] {logging_mixin.py:190} INFO - Failure caused by Found input variables with inconsistent numbers of samples: [1012, 365]
[2025-03-28T14:36:54.457+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=superstore_dag, task_id=forecast_aggregate_sales, run_id=manual__2025-03-28T14:31:30.119149+00:00, execution_date=20250328T143130, start_date=20250328T143653, end_date=20250328T143654
[2025-03-28T14:36:54.496+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-28T14:36:54.499+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 86 for task forecast_aggregate_sales (Found input variables with inconsistent numbers of samples: [1012, 365]; 1389)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/superstore_dag.py", line 218, in forecast_aggregate_sales
    rmse = np.sqrt(mean_squared_error(actual_sales, past_predictions[:len(aggregate_sales_df)]))
  File "/home/airflow/.local/lib/python3.9/site-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/sklearn/metrics/_regression.py", line 565, in mean_squared_error
    _check_reg_targets_with_floating_dtype(
  File "/home/airflow/.local/lib/python3.9/site-packages/sklearn/metrics/_regression.py", line 198, in _check_reg_targets_with_floating_dtype
    y_type, y_true, y_pred, multioutput = _check_reg_targets(
  File "/home/airflow/.local/lib/python3.9/site-packages/sklearn/metrics/_regression.py", line 104, in _check_reg_targets
    check_consistent_length(y_true, y_pred)
  File "/home/airflow/.local/lib/python3.9/site-packages/sklearn/utils/validation.py", line 475, in check_consistent_length
    raise ValueError(
ValueError: Found input variables with inconsistent numbers of samples: [1012, 365]
[2025-03-28T14:36:54.534+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-28T14:36:54.570+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-28T14:36:54.598+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
