[2025-03-28T17:14:35.392+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-28T17:14:35.415+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: superstore_dag.forecast_aggregate_sales manual__2025-03-28T17:14:12.845846+00:00 [queued]>
[2025-03-28T17:14:35.428+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: superstore_dag.forecast_aggregate_sales manual__2025-03-28T17:14:12.845846+00:00 [queued]>
[2025-03-28T17:14:35.431+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-03-28T17:14:35.466+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): forecast_aggregate_sales> on 2025-03-28 17:14:12.845846+00:00
[2025-03-28T17:14:35.487+0000] {standard_task_runner.py:72} INFO - Started process 3670 to run task
[2025-03-28T17:14:35.501+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'superstore_dag', 'forecast_aggregate_sales', 'manual__2025-03-28T17:14:12.845846+00:00', '--job-id', '137', '--raw', '--subdir', 'DAGS_FOLDER/superstore_dag.py', '--cfg-path', '/tmp/tmpihajdgr5']
[2025-03-28T17:14:35.506+0000] {standard_task_runner.py:105} INFO - Job 137: Subtask forecast_aggregate_sales
[2025-03-28T17:14:35.597+0000] {task_command.py:467} INFO - Running <TaskInstance: superstore_dag.forecast_aggregate_sales manual__2025-03-28T17:14:12.845846+00:00 [running]> on host b7fc87b83960
[2025-03-28T17:14:35.750+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='superstore_dag' AIRFLOW_CTX_TASK_ID='forecast_aggregate_sales' AIRFLOW_CTX_EXECUTION_DATE='2025-03-28T17:14:12.845846+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-28T17:14:12.845846+00:00'
[2025-03-28T17:14:35.753+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-28T17:14:35.755+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-28T17:14:35.758+0000] {logging_mixin.py:190} INFO - Current task name:forecast_aggregate_sales state:running start_date:2025-03-28 17:14:35.418264+00:00
[2025-03-28T17:14:35.760+0000] {logging_mixin.py:190} INFO - Dag name:superstore_dag and current dag run status:running
[2025-03-28T17:14:35.762+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-28T17:14:35.828+0000] {forecaster.py:961} INFO - Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
[2025-03-28T17:14:35.857+0000] {filesystem.py:118} DEBUG - input tempfile: /tmp/tmpp7iubxd6/avs_v8qr.json
[2025-03-28T17:14:35.936+0000] {filesystem.py:118} DEBUG - input tempfile: /tmp/tmpp7iubxd6/u2qe44r2.json
[2025-03-28T17:14:35.940+0000] {model.py:2042} DEBUG - idx 0
[2025-03-28T17:14:35.942+0000] {model.py:2043} DEBUG - running CmdStan, num_threads: None
[2025-03-28T17:14:35.945+0000] {model.py:2055} DEBUG - CmdStan args: ['/home/***/.local/lib/python3.9/site-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=42738', 'data', 'file=/tmp/tmpp7iubxd6/avs_v8qr.json', 'init=/tmp/tmpp7iubxd6/u2qe44r2.json', 'output', 'file=/tmp/tmpp7iubxd6/prophet_modelvd9jvkk3/prophet_model-20250328171435.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
[2025-03-28T17:14:35.947+0000] {logging_mixin.py:190} WARNING - 17:14:35 - cmdstanpy - INFO - Chain [1] start processing
[2025-03-28T17:14:35.947+0000] {model.py:2058} INFO - Chain [1] start processing
[2025-03-28T17:14:36.023+0000] {logging_mixin.py:190} WARNING - 17:14:36 - cmdstanpy - INFO - Chain [1] done processing
[2025-03-28T17:14:36.023+0000] {model.py:2115} INFO - Chain [1] done processing
[2025-03-28T17:14:36.371+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/superstore_dag.py", line 203, in forecast_aggregate_sales
    forecast_df[['ds', 'yhat']].assign(label='future')
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/core/frame.py", line 3899, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 6115, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 6176, in _raise_if_missing
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")
KeyError: "None of [Index(['ds', 'yhat'], dtype='object')] are in the [columns]"
[2025-03-28T17:14:36.400+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-28T17:14:36.402+0000] {logging_mixin.py:190} INFO - Task start:2025-03-28 17:14:35.418264+00:00 end:2025-03-28 17:14:36.399782+00:00 duration:0.981518
[2025-03-28T17:14:36.405+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): forecast_aggregate_sales> dag:<DAG: superstore_dag> dagrun:<DagRun superstore_dag @ 2025-03-28 17:14:12.845846+00:00: manual__2025-03-28T17:14:12.845846+00:00, state:running, queued_at: 2025-03-28 17:14:12.869702+00:00. externally triggered: True>
[2025-03-28T17:14:36.407+0000] {logging_mixin.py:190} INFO - Failure caused by "None of [Index(['ds', 'yhat'], dtype='object')] are in the [columns]"
[2025-03-28T17:14:36.410+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=superstore_dag, task_id=forecast_aggregate_sales, run_id=manual__2025-03-28T17:14:12.845846+00:00, execution_date=20250328T171412, start_date=20250328T171435, end_date=20250328T171436
[2025-03-28T17:14:36.447+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-28T17:14:36.450+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 137 for task forecast_aggregate_sales ("None of [Index(['ds', 'yhat'], dtype='object')] are in the [columns]"; 3670)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/superstore_dag.py", line 203, in forecast_aggregate_sales
    forecast_df[['ds', 'yhat']].assign(label='future')
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/core/frame.py", line 3899, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 6115, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 6176, in _raise_if_missing
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")
KeyError: "None of [Index(['ds', 'yhat'], dtype='object')] are in the [columns]"
[2025-03-28T17:14:36.487+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-28T17:14:36.520+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-28T17:14:36.543+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
