[2025-03-29T05:54:59.138+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-29T05:54:59.163+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: forecast_sales_dag.forecast_aggregate_sales manual__2025-03-29T05:54:56.022481+00:00 [queued]>
[2025-03-29T05:54:59.177+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: forecast_sales_dag.forecast_aggregate_sales manual__2025-03-29T05:54:56.022481+00:00 [queued]>
[2025-03-29T05:54:59.182+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-03-29T05:54:59.235+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): forecast_aggregate_sales> on 2025-03-29 05:54:56.022481+00:00
[2025-03-29T05:54:59.245+0000] {standard_task_runner.py:72} INFO - Started process 1848 to run task
[2025-03-29T05:54:59.250+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'forecast_sales_dag', 'forecast_aggregate_sales', 'manual__2025-03-29T05:54:56.022481+00:00', '--job-id', '252', '--raw', '--subdir', 'DAGS_FOLDER/forecast_etl.py', '--cfg-path', '/tmp/tmpwvxosyim']
[2025-03-29T05:54:59.253+0000] {standard_task_runner.py:105} INFO - Job 252: Subtask forecast_aggregate_sales
[2025-03-29T05:54:59.350+0000] {task_command.py:467} INFO - Running <TaskInstance: forecast_sales_dag.forecast_aggregate_sales manual__2025-03-29T05:54:56.022481+00:00 [running]> on host 2eb76630dc09
[2025-03-29T05:54:59.493+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='forecast_sales_dag' AIRFLOW_CTX_TASK_ID='forecast_aggregate_sales' AIRFLOW_CTX_EXECUTION_DATE='2025-03-29T05:54:56.022481+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-29T05:54:56.022481+00:00'
[2025-03-29T05:54:59.497+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-29T05:54:59.499+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-29T05:54:59.502+0000] {logging_mixin.py:190} INFO - Current task name:forecast_aggregate_sales state:running start_date:2025-03-29 05:54:59.165814+00:00
[2025-03-29T05:54:59.503+0000] {logging_mixin.py:190} INFO - Dag name:forecast_sales_dag and current dag run status:running
[2025-03-29T05:54:59.506+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-29T05:54:59.567+0000] {forecaster.py:961} INFO - Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
[2025-03-29T05:54:59.591+0000] {filesystem.py:118} DEBUG - input tempfile: /tmp/tmp_5kne0g9/v9aeom8z.json
[2025-03-29T05:54:59.698+0000] {filesystem.py:118} DEBUG - input tempfile: /tmp/tmp_5kne0g9/phr3rkbd.json
[2025-03-29T05:54:59.702+0000] {model.py:2042} DEBUG - idx 0
[2025-03-29T05:54:59.704+0000] {model.py:2043} DEBUG - running CmdStan, num_threads: None
[2025-03-29T05:54:59.706+0000] {model.py:2055} DEBUG - CmdStan args: ['/home/***/.local/lib/python3.9/site-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=93561', 'data', 'file=/tmp/tmp_5kne0g9/v9aeom8z.json', 'init=/tmp/tmp_5kne0g9/phr3rkbd.json', 'output', 'file=/tmp/tmp_5kne0g9/prophet_modelo4_jfbfz/prophet_model-20250329055459.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
[2025-03-29T05:54:59.709+0000] {logging_mixin.py:190} WARNING - 05:54:59 - cmdstanpy - INFO - Chain [1] start processing
[2025-03-29T05:54:59.709+0000] {model.py:2058} INFO - Chain [1] start processing
[2025-03-29T05:54:59.775+0000] {logging_mixin.py:190} WARNING - 05:54:59 - cmdstanpy - INFO - Chain [1] done processing
[2025-03-29T05:54:59.775+0000] {model.py:2115} INFO - Chain [1] done processing
[2025-03-29T05:55:00.132+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/forecast_etl.py", line 53, in forecast_aggregate_sales
    past_future_sales.to_csv(os.path.join(OUTPUT_DIR, 'past_future_sales.csv'), index=False)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/core/generic.py", line 3902, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/formats/format.py", line 1152, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/formats/csvs.py", line 247, in save
    with get_handle(
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
PermissionError: [Errno 13] Permission denied: '/opt/airflow/logs/extracted_data/past_future_sales.csv'
[2025-03-29T05:55:00.159+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-29T05:55:00.162+0000] {logging_mixin.py:190} INFO - Task start:2025-03-29 05:54:59.165814+00:00 end:2025-03-29 05:55:00.159216+00:00 duration:0.993402
[2025-03-29T05:55:00.164+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): forecast_aggregate_sales> dag:<DAG: forecast_sales_dag> dagrun:<DagRun forecast_sales_dag @ 2025-03-29 05:54:56.022481+00:00: manual__2025-03-29T05:54:56.022481+00:00, state:running, queued_at: 2025-03-29 05:54:56.034754+00:00. externally triggered: True>
[2025-03-29T05:55:00.166+0000] {logging_mixin.py:190} INFO - Failure caused by [Errno 13] Permission denied: '/opt/***/logs/extracted_data/past_future_sales.csv'
[2025-03-29T05:55:00.168+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=forecast_sales_dag, task_id=forecast_aggregate_sales, run_id=manual__2025-03-29T05:54:56.022481+00:00, execution_date=20250329T055456, start_date=20250329T055459, end_date=20250329T055500
[2025-03-29T05:55:00.280+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-29T05:55:00.282+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 252 for task forecast_aggregate_sales ([Errno 13] Permission denied: '/opt/airflow/logs/extracted_data/past_future_sales.csv'; 1848)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/forecast_etl.py", line 53, in forecast_aggregate_sales
    past_future_sales.to_csv(os.path.join(OUTPUT_DIR, 'past_future_sales.csv'), index=False)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/core/generic.py", line 3902, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/formats/format.py", line 1152, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/formats/csvs.py", line 247, in save
    with get_handle(
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
PermissionError: [Errno 13] Permission denied: '/opt/airflow/logs/extracted_data/past_future_sales.csv'
[2025-03-29T05:55:00.307+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-29T05:55:00.343+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-29T05:55:00.365+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
